name: Run Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      project:
        description: 'Playwright project to use for running the tests'
        required: false
        default: ''

env:
  ALLURE_RESULTS_PATH: allure-results

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests (projects defined as input)
      if: github.event.inputs.project != ''
      run: npx playwright test --project ${{ github.event.inputs.project }}
    - name: Run Playwright tests (all projects)
      if: github.event.inputs.project == ''
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Get Allure history # Step to retrieve Allure history
      uses: actions/checkout@v3
      if: always() # Execute even if previous steps fail
      continue-on-error: true # Continue execution even if the step fails
      with:
        ref: gh-pages # Specify the branch to retrieve Allure history from
        path: gh-pages # Set the destination path for Allure history

    - name: Allure report action # Step to generate Allure report
      uses: simple-elf/allure-report-action@master
      if: always() # Execute even if previous steps fail
      with:
        allure_results: "$ALLURE_RESULTS_PATH" # Specify the directory containing Allure results
        allure_history: allure-history # Specify the directory to store Allure history
        keep_reports: 5 # Specify the number of previous reports to keep

    - name: Deploy Allure report to GitHub Pages # Step to deploy Allure report to GitHub Pages
      if: always() # Execute even if previous steps fail
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Provide the GitHub token for authentication
        publish_branch: gh-pages # Specify the branch to publish the report to
        publish_dir: allure-history # Specify the directory containing the report